version: '3.9'

services:
  nestapp:
    container_name: nestapp-container
    image: kathir/nestapp:latest
    build: .
    ports:
      - 3000:3000
    env_file:
      - .env
    depends_on:
      - db
  db:
    container_name: db
    image: postgres:14
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - db_data:/var/lib/postgresql/data
volumes:
  db_data: {}
